import Testing
import SECP256K1

/// The complete BIP340 vector set, from `BIP340Vectors.swift` (generated by
/// `swift-tools/generate-bip340-vectors.py` out of upstream's own C tests).
///
/// The earlier Schnorr suite checks vector 0 by hand. This one runs all 19,
/// including the four that use BIP340's arbitrary-size message extension
/// (message lengths 0, 1, 17 and 100 bytes) and the two whose public key is not
/// a valid x coordinate.
@Suite("BIP340 vectors")
struct BIP340VectorTests {
    @Test("the generated vector set is intact")
    func vectorSetIsIntact() {
        // Guard against the generator silently producing nothing useful.
        #expect(bip340Vectors.count == 19)
        #expect(bip340Vectors.filter { !$0.publicKeyParses }.count == 2)
        #expect(bip340Vectors.filter { $0.secretKey != nil }.count == 8)
        #expect(bip340Vectors.filter { $0.verifies }.count == 9)
        let lengths = Set(bip340Vectors.map(\.message.count))
        #expect(lengths == [0, 1, 17, 32, 100])
    }

    @Test("every vector's public key parses exactly as specified")
    func publicKeyParsing() throws {
        let ctx = try Context()
        for vector in bip340Vectors {
            let parsed = try? ctx.xOnlyPublicKey(parsing: vector.publicKey.span)
            #expect((parsed != nil) == vector.publicKeyParses, "\(vector.name)")
        }
    }

    @Test("every verification vector gives the specified result")
    func verification() throws {
        let ctx = try Context()
        var checked = 0
        for vector in bip340Vectors {
            guard vector.publicKeyParses, let signature = vector.signature else { continue }
            let key = try ctx.xOnlyPublicKey(parsing: vector.publicKey.span)
            let ok = ctx.isValidSchnorr(signature.span,
                                        message: vector.message.span,
                                        publicKey: key)
            checked += 1
            #expect(ok == vector.verifies, "\(vector.name)")
        }
        #expect(checked == 17)   // 19 minus the two unparseable keys
    }

    @Test("every signing vector reproduces the specified signature byte for byte")
    func signing() throws {
        let ctx = try Context()
        var checked = 0
        for vector in bip340Vectors {
            guard let secretKey = vector.secretKey,
                  let auxRandom = vector.auxRandom,
                  let expected = vector.signature else { continue }

            let keyPair = try ctx.keyPair(secretKey: secretKey.span)

            // The derived x-only key must match the vector's public key.
            let (derived, _) = try ctx.xOnlyPublicKey(of: keyPair)
            #expect(ctx.serializedBytes(of: derived) == vector.publicKey, "\(vector.name)")

            // Sign through the arbitrary-length path, which every vector can use.
            let produced = try ctx.signSchnorr(message: vector.message.span,
                                               keyPair: keyPair,
                                               auxiliaryRandom: auxRandom.span)
            #expect(produced == expected, "\(vector.name)")

            // For 32-byte messages the dedicated entry point must agree, which
            // is the same cross-check upstream's own runner performs.
            if vector.message.count == 32 {
                let via32 = try ctx.signSchnorr(message32: vector.message.span,
                                                keyPair: keyPair,
                                                auxiliaryRandom: auxRandom.span)
                #expect(via32 == expected, "\(vector.name) via signSchnorr(message32:)")
            }
            checked += 1
        }
        #expect(checked == 8)
    }
}
