import Testing
import Foundation
import SECP256K1

/// BIP352 silent-payment vectors, both directions.
///
/// Driven by `bip352-vectors.json`, generated by
/// `swift-tools/generate-bip352-vectors.py` from upstream's own pre-processed
/// `src/modules/silentpayments/vectors.h`.
///
/// Upstream's raw JSON is not usable directly: its `vin` entries are
/// transaction inputs, so recovering the input public keys needs Bitcoin script
/// parsing (P2TR, P2WPKH, P2PKH, P2SH-P2WPKH). `vectors.h` is upstream's
/// resolved form, which is why upstream's own C runner uses it as well.
@Suite("BIP352 vectors")
struct BIP352VectorTests {
    struct Recipient: Decodable {
        let scan_pubkey: String
        let spend_pubkey: String
        let count: Int
    }

    struct ReceiveSubtest: Decodable {
        let scan_seckey: String
        let spend_seckey: String
        let to_scan_outputs: [String]
        let labels: [UInt32]
        let full_check: Int
        let found_output_pubkeys: [String]
        let found_seckey_tweaks: [String]
    }

    struct Vector: Decodable {
        let plain_seckeys: [String]
        let plain_pubkeys: [String]
        let taproot_seckeys: [String]
        let xonly_pubkeys: [String]
        let outpoint_smallest: String
        let num_outputs: Int
        let recipients: [Recipient]
        let expected_output_sets: [[String]]
        let receive_subtests: [ReceiveSubtest]
    }

    static func load() throws -> [Vector] {
        let url = Vectors.repositoryRoot
            .appending(path: "swift-test/SECP256K1Test/bip352-vectors.json")
        return try JSONDecoder().decode([Vector].self, from: try Data(contentsOf: url))
    }

    static func bytes(_ hex: String) -> [UInt8] { Vectors.bytes(fromHex: hex) }

    @Test("the generated vector file is intact")
    func vectorsIntact() throws {
        let vectors = try Self.load()
        #expect(vectors.count == 28)
        #expect(vectors.flatMap(\.receive_subtests).count == 29)
    }

    @Test("sending reproduces the expected outputs for every vector")
    func sending() throws {
        let ctx = try Context()
        var checked = 0
        for (index, v) in try Self.load().enumerated() {
            // An empty expected set is how upstream encodes "sending must not
            // produce outputs": vector 25 has no valid inputs, vector 26's
            // input keys sum to the point at infinity, and vector 28 exceeds
            // BIP352's per-group recipient limit. For those, the wrapper
            // throwing is the correct outcome, so failure is asserted rather
            // than reported.
            let expectsNoOutputs = v.expected_output_sets.allSatisfy(\.isEmpty)
            do {
                // A recipient entry carries a count: one entry may receive
                // several outputs, so expand into the flat list the wrapper
                // takes.
                var recipients: [SilentPaymentRecipient] = []
                for entry in v.recipients {
                    let scan = try ctx.publicKey(parsing: Self.bytes(entry.scan_pubkey).span)
                    let spend = try ctx.publicKey(parsing: Self.bytes(entry.spend_pubkey).span)
                    for _ in 0..<entry.count {
                        recipients.append(SilentPaymentRecipient(scanPublicKey: scan,
                                                                 spendPublicKey: spend))
                    }
                }
                guard !recipients.isEmpty, !v.expected_output_sets.isEmpty else { continue }
                // Vector 25 has no input keys at all, so there is nothing to
                // hand the sender; it is covered by the receiving test.

                let keyPairs = try v.taproot_seckeys.map {
                    try ctx.keyPair(secretKey: Self.bytes($0).span)
                }
                let secretKeys = v.plain_seckeys.map { Self.bytes($0) }
                guard !keyPairs.isEmpty || !secretKeys.isEmpty else { continue }

                let outpoint = Self.bytes(v.outpoint_smallest)
                let outputs = try ctx.silentPaymentOutputs(
                    recipients: recipients,
                    smallestOutpoint36: outpoint.span,
                    keyPairs: keyPairs,
                    secretKeys: secretKeys)

                let produced = Set(outputs.map { ctx.serializedBytes(of: $0) })
                if expectsNoOutputs {
                    #expect(produced.isEmpty,
                            "vector \(index + 1): expected no outputs, got \(produced.count)")
                } else {
                    // BIP352 groups outputs per scan key, so several orderings
                    // are acceptable; upstream lists each permutation.
                    let acceptable = v.expected_output_sets.map { Set($0.map(Self.bytes)) }
                    #expect(acceptable.contains(produced), "vector \(index + 1)")
                }
                checked += 1
            } catch {
                // Throwing is the expected result for the failure vectors.
                #expect(expectsNoOutputs,
                        "vector \(index + 1) (sending) failed unexpectedly: \(error)")
                checked += 1
            }
        }
        #expect(checked >= 20)
    }

    @Test("scanning finds the expected outputs and tweaks for every subtest")
    func receiving() throws {
        let ctx = try Context()
        var checkedSubtests = 0
        for (index, v) in try Self.load().enumerated() {
            // Vector 26's input keys sum to the point at infinity, so the
            // recipient cannot build a prevouts summary at all -- which is
            // precisely "receiver skips tx". A throw is therefore correct
            // whenever every subtest expects to find nothing.
            let expectsNothing = v.receive_subtests.allSatisfy(\.found_output_pubkeys.isEmpty)
            do {
                let outpoint = Self.bytes(v.outpoint_smallest)
                let xonly = try v.xonly_pubkeys.map {
                    try ctx.xOnlyPublicKey(parsing: Self.bytes($0).span)
                }
                let plain = try v.plain_pubkeys.map {
                    try ctx.publicKey(parsing: Self.bytes($0).span)
                }
                guard !xonly.isEmpty || !plain.isEmpty else { continue }

                let summary = try ctx.silentPaymentPrevoutsSummary(
                    smallestOutpoint36: outpoint.span,
                    xOnlyPublicKeys: xonly,
                    publicKeys: plain)

                for subtest in v.receive_subtests {
                    let scanKey = Self.bytes(subtest.scan_seckey)
                    let spendKey = Self.bytes(subtest.spend_seckey)
                    let spendPub = try ctx.publicKey(secretKey: spendKey.span)

                    // The recipient's label cache, for this subtest's labels.
                    var labelTweaks: [[UInt8]: [UInt8]] = [:]
                    for m in subtest.labels {
                        let (label, tweak) = try ctx.silentPaymentLabel(
                            scanKey32: scanKey.span, m: m)
                        labelTweaks[ctx.serializedBytes(of: label)] = tweak
                    }

                    let toScan = try subtest.to_scan_outputs.map {
                        try ctx.xOnlyPublicKey(parsing: Self.bytes($0).span)
                    }
                    let found = try ctx.scanSilentPaymentOutputs(
                        txOutputs: toScan,
                        scanKey32: scanKey.span,
                        prevoutsSummary: summary,
                        unlabeledSpendPublicKey: spendPub,
                        labelLookup: { labelTweaks[$0] })

                    // full_check is upstream's own flag, documented in
                    // vectors.h as "1..detailed check against tweaks and
                    // signatures, 0..only check found outputs count". Vector 28
                    // uses 0 and leaves its expected pubkeys zero-filled, so
                    // comparing contents there would compare against padding.
                    if subtest.full_check == 1 {
                        // Compared as sets: scanning order need not match the
                        // vector's listing.
                        let expectedOutputs = Set(subtest.found_output_pubkeys.map(Self.bytes))
                        let producedOutputs = Set(found.map { ctx.serializedBytes(of: $0.output) })
                        #expect(producedOutputs == expectedOutputs,
                                "vector \(index + 1): output set")

                        let expectedTweaks = Set(subtest.found_seckey_tweaks.map(Self.bytes))
                        let producedTweaks = Set(found.map(\.tweak))
                        #expect(producedTweaks == expectedTweaks,
                                "vector \(index + 1): tweak set")
                    } else {
                        #expect(found.count == subtest.found_output_pubkeys.count,
                                "vector \(index + 1): found-output count")
                    }
                    checkedSubtests += 1
                }
            } catch {
                #expect(expectsNothing,
                        "vector \(index + 1) (receiving) failed unexpectedly: \(error)")
            }
        }
        #expect(checkedSubtests >= 25)
    }
}
